# Expriment no:-1
## Develop a python program to read n digit integer number,and separete the integre number and display each digit.

In [3]:
n=int(input("Enter the number of digits:"))
if n>0:
    number=int(input(f"Enter a {n}-digit integer:"))
    if number>=10**(n-1) and number<10**n:
        for i in range(n):
            digit=number//(10**(n-1))
            print(digit)
            number%=10**(n-1)
            n-=1
    else:
        print(f"Please enter a {n}-digit integer;")
else:
    print("Please enter a valid number of digits(greater than 0).")

Enter the number of digits:3
Enter a 3-digit integer:123
1
2
3


# Experiment no:-2
## Develop a python program to accept 4 numbers and display them in sorted order using a minimum number of if-else statements.

In [2]:
a=int(input("Enter the first number:"))
b=int(input("Enter the second number:"))
c=int(input("Enter the third number:"))
d=int(input("Enter the fourth number:"))
if a<b:a,b=b,a
if c<d:c,d=d,c
if a<c:a,c=c,a
if b<d:b,d=d,b
if b<c:b,c=c,b
print("The sorted numbers are:",a,b,c,d)

Enter the first number:7
Enter the second number:4
Enter the third number:3
Enter the fourth number:5
The sorted numbers are: 7 5 4 3


# Experiment no:-4
## Develop a program for checking if a given digit is palindrome or not.

In [3]:
number=int(input("Enter an n-digit number:"))
original_number=number
reversed_number=0
while number>0:
    digit=number%10
    reversed_number=reversed_number*10+digit
    number//=10
if original_number==reversed_number:
    print("Palindrome.")
else:
    print("Not a palindrome.")

Enter an n-digit number:1234
Not a palindrome.


# Experiment no:-5
## Develop a python script to display a multiplication table for given integer n.


In [5]:
n=int(input("Enter an integer for multiplication table:"))
print(f"Multiplication Table for {n}:")
for i in range(1,11):
    result=n*i
    print(f"{n}x{i}={result}")

Enter an integer for multiplication table:2
Multiplication Table for 2:
2x1=2
2x2=4
2x3=6
2x4=8
2x5=10
2x6=12
2x7=14
2x8=16
2x9=18
2x10=20


# Experiment no:-3
## Develop python scripts to calculate the mean,median,mode,variance and standard deviation of n integer numbers

In [6]:
n=int(input("Enter the number of elements:"))
numbers=[int(input(f"Enter number {i+1}:")) for i in range(n)]
mean=sum(numbers)/n
numbers.sort()
if n%2==0:
    median=(numbers[n//2-1]+numbers[n//2])/2
else:
    median=numbers[n//2]
frequency={num:numbers.count(num) for num in numbers}
max_count=max(frequency.values())
mode=[k for k,v in frequency.items() if v==max_count]
if len(mode)==n:
    mode="No mode"
mean_difference_squared_sum=sum((x-mean)**2 for x in numbers)
variance_sample=mean_difference_squared_sum/(n-1) if n>1 else 0
variance_population=mean_difference_squared_sum/n
std_deviation_sample=variance_sample**0.5
std_deviation_population=variance_population**0.5
print(f"Mean={mean}")
print(f"Median={median}")
print(f"Mode={mode}")
print(f"Sample variance={variance_sample}")
print(f"Population variance={variance_population}")
print(f"Sample standard deviation={std_deviation_sample}")
print(f"Sample population deviation={std_deviation_population}")
                   

Enter the number of elements:6
Enter number 1:4
Enter number 2:8
Enter number 3:6
Enter number 4:5
Enter number 5:3
Enter number 6:9
Mean=5.833333333333333
Median=5.5
Mode=No mode
Sample variance=5.366666666666667
Population variance=4.472222222222222
Sample standard deviation=2.316606713852541
Sample population deviation=2.1147629234082532


# Experiment no:-6
## Develop a python script to rotate right about a given position in that list and display them.

In [5]:
number=int(input("Enter the integer number:"))
revs_number=0
while(number>0):
    remainder=number%10
    revs_number=(revs_number*10)+remainder
    number=number//10
print("The reverse number is:{}".format(revs_number))

Enter the integer number:253
The reverse number is:352


# Expriment no:-7
## Develop a python program to interchange the digits of a given number.

In [5]:
def interchange_digits(number,pos1,pos2):
    number_str=str(number)
    number_list=list(number_str)
    number_list[pos1-1],number_list[pos2-1]=number_list[pos2-1],number_list[pos1-1]
    interchanged_number=int(''.join(number_list))
    return interchanged_number
number=int(input('Enter the user input:'))
pos1=int(input('Enter the 1st position which u want to swap:'))
pos2=int(input('Enter the 2st position which u want to swap:'))
interchanged_number=interchange_digits(number,pos1,pos2)
print("Original number:",number)
print("Interchanged number:",interchanged_number)

Enter the user input:23456
Enter the 1st position which u want to swap:2
Enter the 2st position which u want to swap:4
Original number: 23456
Interchanged number: 25436


# Experiment no:-8
## Develop a python program to capitalize a given list of string.

In [3]:
def capitalize_strings(string_list):
    return[s.capitalize() for s in string_list]
input_strings=['hello','good','how','simple']
capitalize_strings=capitalize_strings(input_strings)
print(capitalize_strings)

['Hello', 'Good', 'How', 'Simple']


# Experiment no:-9
## Using a dictionary,develop a python program to determine and print the number of duplicate words in a sentence.

In [9]:
def count_duplicate_words(sentence):
    words=sentence.split()
    word_count={}
    for word in words:
        word=word.lower()
        if word in word_count:
            word_count[word]+=1
        else:
            word_count[word]=1
    duplicates={word:count for word,count in word_count.items() if count>1}
    if duplicates:
        print("Duplicate words and their counts:")
        for word,count in duplicates.items():
            print(f"{word}:{count}")
    else:
        print("No duplicate words found.")
sentence=input("Enter a sentence:")
count_duplicate_words(sentence)

Enter a sentence:Big black bug bit a big black dog on his big black nose.
Duplicate words and their counts:
big:3
black:3


# Experiment no:-10
## Develop a python program to read Numpy array and print row(sum,mean,std) and column(sum,mean,std).

In [2]:
from numpy import asarray
data=[[1,2,3],[4,5,6]]
data=asarray(data)
print("Numpy Array")
print(data)
print("__________________________________________________________________________________")
totalr=data.sum(axis=1)
totalc=data.sum(axis=0)
print("Row Sum")
print(totalr)
print("Column Sum")
print(totalc)
print("__________________________________________________________________________________")
meanr=data.mean(axis=1)
meanc=data.mean(axis=0)
print("Row Mean")
print(meanr)
print("Column Mean")
print(meanc)
print("__________________________________________________________________________________")
stdr=data.std(axis=1)
stdc=data.std(axis=0)
print("Row STD")
print(stdr)
print("Column STD")
print(stdc)

Numpy Array
[[1 2 3]
 [4 5 6]]
__________________________________________________________________________________
Row Sum
[ 6 15]
Column Sum
[5 7 9]
__________________________________________________________________________________
Row Mean
[2. 5.]
Column Mean
[2.5 3.5 4.5]
__________________________________________________________________________________
Row STD
[0.81649658 0.81649658]
Column STD
[1.5 1.5 1.5]


# Experiment no:-11
## Develop a Python program to read and print in the console CSV file.

In [5]:
import csv
file=open('employee_birthday.csv',mode='r') 
csv_reader=csv.reader(file,delimiter=',')
line_count=0
for row in csv_reader:
    if line_count==0:
        print(f'Column names are {", ".join(row)}')
        line_count+=1
    else:
        print(f'\t{row[0]} works in the {row[1]} department, and was born in {row[2]}.')
        line_count+=1
print(f'Processed {line_count} lines.')

Column names are Name, Department, Birthday_month
	John Smith works in the Accounting department, and was born in November.
	Erica Meyers works in the IT department, and was born in March.
	Rocky works in the HR department, and was born in April.
Processed 4 lines.


# Experiment no:-12
## Develop a Python program to read a HTML file with basic tags,and construct a directory and display the same in the console.

In [4]:
import pandas as pd
def read_html_to_dict(html_file):
    tables=pd.read_html(html_file)
    tables_dict={}
    for i,table in enumerate(tables):
        table_dict=table.to_dict(orient='list')
        tables_dict[f'Table_{i+1}']=table_dict
    return tables_dict
if __name__=='__main__':
    html_file='sample.html'
    result=read_html_to_dict(html_file)
    print(result)

{'Table_1': {'Name': ['Alice', 'Bob'], 'Age': [24, 27]}, 'Table_2': {'Country': ['France', 'Italy'], 'Capital': ['Paris', 'Rome']}}
